/*
*サビの動き
*Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, {useEffect} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Segmentmiku({ ...props }) {
  const { nodes, materials, animations } = useGLTF('/model/miku_segment.glb')
  const { ref, actions, names } = useAnimations(animations)

  useEffect(() => {
    for(let i=0;i<=20;i++){
      actions[names[i]].reset().play()
    }
  }, [])

  return (
<group ref={ref} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="立方体003" castShadow receiveShadow geometry={nodes.立方体003.geometry} material={materials['マテリアル.015']} position={[0.84, 5.71, 1.46]} rotation={[-3.14, 0.01, 3.14]} scale={[0.13, 0.21, 0.13]} />
        <mesh name="立方体006" castShadow receiveShadow geometry={nodes.立方体006.geometry} material={materials['マテリアル.005']} position={[-0.75, 5.71, 1.46]} rotation={[-3.14, 0.01, 3.14]} scale={[0.13, 0.21, 0.13]} />
        <mesh name="Cube" castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials.face} position={[0.07, 6.68, -0.4]} rotation={[-3.14, 0.01, 3.14]} scale={[2.24, 2.24, 1.58]} />
        <mesh name="Cube002" castShadow receiveShadow geometry={nodes.Cube002.geometry} material={materials.face} position={[0.1, 4.25, -0.4]} rotation={[-Math.PI, 0.01, -Math.PI]} scale={[0.56, 0.29, 0.56]} />
        <group name="Cube003" position={[0.1, 2.97, -0.4]} rotation={[-Math.PI, 0.01, -Math.PI]} scale={[1.62, 1.25, 0.81]}>
          <mesh name="Cube003_1" castShadow receiveShadow geometry={nodes.Cube003_1.geometry} material={materials.huku} />
          <mesh name="Cube003_2" castShadow receiveShadow geometry={nodes.Cube003_2.geometry} material={materials['マテリアル.014']} />
        </group>
        <group name="Cube004" position={[0.1, 2.33, -0.4]} rotation={[-Math.PI, 0.01, -Math.PI]} scale={[1.57, 1.08, 0.81]}>
          <mesh name="Cube004_1" castShadow receiveShadow geometry={nodes.Cube004_1.geometry} material={materials.Material} />
          <mesh name="Cube004_2" castShadow receiveShadow geometry={nodes.Cube004_2.geometry} material={materials['マテリアル.003']} />
          <mesh name="Cube004_3" castShadow receiveShadow geometry={nodes.Cube004_3.geometry} material={materials.skirt} />
        </group>
        <mesh name="Cube005" castShadow receiveShadow geometry={nodes.Cube005.geometry} material={materials['マテリアル.009']} position={[-0.72, 1.1, -0.41]} rotation={[-Math.PI, 0.01, -Math.PI]} scale={[0.38, 0.36, 0.34]} />
        <group name="平面" position={[-1.42, 3.62, -0.42]} rotation={[-3.14, 0.01, -1.32]} scale={[0.45, 2.48, 0.42]}>
          <mesh name="平面_1" castShadow receiveShadow geometry={nodes.平面_1.geometry} material={materials.face} />
          <mesh name="平面_2" castShadow receiveShadow geometry={nodes.平面_2.geometry} material={materials['マテリアル.002']} />
          <mesh name="平面_3" castShadow receiveShadow geometry={nodes.平面_3.geometry} material={materials['マテリアル.013']} />
        </group>
        <group name="飾り_右" position={[-2.94, 7.21, -0.46]} rotation={[-0.78, -0.06, -3.09]} scale={[0.54, 1.18, 1.18]}>
          <mesh name="Cube007" castShadow receiveShadow geometry={nodes.Cube007.geometry} material={materials['wa.black']} />
          <mesh name="Cube007_1" castShadow receiveShadow geometry={nodes.Cube007_1.geometry} material={materials['wa.red']} />
        </group>
        <mesh name="平面001" castShadow receiveShadow geometry={nodes.平面001.geometry} material={materials['hair.001']} position={[-1.36, 7.44, -0.45]} rotation={[1.57, -0.01, 1.58]} scale={-0.74} />
        <mesh name="Cube008" castShadow receiveShadow geometry={nodes.Cube008.geometry} material={materials.hair} position={[0.07, 6.92, -0.4]} rotation={[-3.14, 0.01, 3.14]} scale={[-2.42, -2.02, -1.7]} />
        <mesh name="立方体001" castShadow receiveShadow geometry={nodes.立方体001.geometry} material={materials.huku} position={[-0.36, 3.82, 0.64]} rotation={[Math.PI, 0.01, -1.01]} scale={[0.23, 0.38, 0.24]} />
        <mesh name="立方体" castShadow receiveShadow geometry={nodes.立方体.geometry} material={materials['マテリアル.004']} position={[0.21, 2.86, 0.62]} rotation={[3.03, 0.01, -3.14]} scale={[0.95, 0.95, 0.06]} />
        <mesh name="平面002" castShadow receiveShadow geometry={nodes.平面002.geometry} material={materials['hair.001']} position={[1.5, 7.45, -0.42]} rotation={[-Math.PI / 2, 0, 1.56]} scale={0.74} />
        <group name="飾り_左" position={[3.08, 7.21, -0.39]} rotation={[0.78, -0.06, -0.05]} scale={[-0.54, -1.18, -1.18]}>
          <mesh name="Cube001_1" castShadow receiveShadow geometry={nodes.Cube001_1.geometry} material={materials['wa.black']} />
          <mesh name="Cube001_2" castShadow receiveShadow geometry={nodes.Cube001_2.geometry} material={materials['wa.red']} />
        </group>
        <mesh name="Cube011" castShadow receiveShadow geometry={nodes.Cube011.geometry} material={materials.hair} position={[0.07, 6.92, -0.4]} rotation={[0, -0.01, -3.14]} scale={[2.42, 2.02, 1.7]} />
        <mesh name="Cube012" castShadow receiveShadow geometry={nodes.Cube012.geometry} material={materials['マテリアル.010']} position={[0.92, 1.1, -0.39]} rotation={[-Math.PI, 0.01, -Math.PI]} scale={[0.38, 0.36, 0.34]} />
        <mesh name="Cube014" castShadow receiveShadow geometry={nodes.Cube014.geometry} material={materials['マテリアル.011']} position={[0.93, 0.51, -0.41]} rotation={[Math.PI / 2, 0, -3.13]} scale={[0.41, 0.39, 0.41]} />
        <mesh name="Cube001" castShadow receiveShadow geometry={nodes.Cube001.geometry} material={materials['マテリアル.011']} position={[-0.73, 0.51, -0.43]} rotation={[Math.PI / 2, 0, -3.13]} scale={[0.41, 0.39, 0.41]} />
        <group name="平面003" position={[1.62, 3.62, -0.38]} rotation={[0, -0.01, 1.82]} scale={[0.45, 2.48, 0.42]}>
          <mesh name="平面004" castShadow receiveShadow geometry={nodes.平面004.geometry} material={materials.face} />
          <mesh name="平面004_1" castShadow receiveShadow geometry={nodes.平面004_1.geometry} material={materials['マテリアル.002']} />
          <mesh name="平面004_2" castShadow receiveShadow geometry={nodes.平面004_2.geometry} material={materials['マテリアル.013']} />
        </group>
        <mesh name="立方体004" castShadow receiveShadow geometry={nodes.立方体004.geometry} material={materials.huku} position={[0.52, 3.82, 0.64]} rotation={[0, 0, 2.13]} scale={[0.23, 0.38, 0.24]} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/miku_segment.glb')
