/*
*歩く
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, {useEffect} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Walkmiku({ ...props }) {
  const { nodes, materials, animations } = useGLTF('/model/miku_walk.glb')
  const { ref, actions, names } = useAnimations(animations)

  useEffect(() => {
    for(let i=0;i<=7;i++){
      actions[names[i]].reset().play()
    }
  }, [])

  return (
    <group ref={ref} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="立方体002" castShadow receiveShadow geometry={nodes.立方体002.geometry} material={materials['マテリアル.015']} position={[-1.66, 5.71, 0.22]} rotation={[-3.14, 0.91, 3.14]} scale={[0.13, 0.21, 0.13]} />
        <mesh name="立方体003" castShadow receiveShadow geometry={nodes.立方体003.geometry} material={materials['マテリアル.015']} position={[-0.68, 5.71, 1.47]} rotation={[-3.14, 0.91, 3.14]} scale={[0.13, 0.21, 0.13]} />
        <mesh name="Cube" castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials.face} position={[0.3, 6.68, -0.29]} rotation={[-3.14, 0.91, 3.14]} scale={[2.24, 2.24, 1.58]} />
        <mesh name="Cube002" castShadow receiveShadow geometry={nodes.Cube002.geometry} material={materials.face} position={[0.32, 4.25, -0.27]} rotation={[-Math.PI, 0.91, -Math.PI]} scale={[0.56, 0.29, 0.56]} />
        <group name="Cube003" position={[0.32, 2.97, -0.27]} rotation={[-Math.PI, 0.91, -Math.PI]} scale={[1.62, 1.25, 0.81]}>
          <mesh name="Cube003_1" castShadow receiveShadow geometry={nodes.Cube003_1.geometry} material={materials.huku} />
          <mesh name="Cube003_2" castShadow receiveShadow geometry={nodes.Cube003_2.geometry} material={materials['マテリアル.014']} />
        </group>
        <group name="Cube004" position={[0.32, 2.33, -0.27]} rotation={[-Math.PI, 0.91, -Math.PI]} scale={[1.57, 1.08, 0.81]}>
          <mesh name="Cube004_1" castShadow receiveShadow geometry={nodes.Cube004_1.geometry} material={materials.Material} />
          <mesh name="Cube004_2" castShadow receiveShadow geometry={nodes.Cube004_2.geometry} material={materials['マテリアル.003']} />
          <mesh name="Cube004_3" castShadow receiveShadow geometry={nodes.Cube004_3.geometry} material={materials.skirt} />
        </group>
        <mesh name="Cube005" castShadow receiveShadow geometry={nodes.Cube005.geometry} material={materials['マテリアル.009']} position={[-0.18, 2.11, -0.92]} rotation={[-Math.PI, 0.91, -Math.PI]} scale={[0.38, 0.73, 0.34]} />
        <group name="平面" position={[-0.61, 3.62, -1.48]} rotation={[-3.13, 0.91, -1.33]} scale={[0.45, 2.48, 0.42]}>
          <mesh name="平面_1" castShadow receiveShadow geometry={nodes.平面_1.geometry} material={materials.face} />
          <mesh name="平面_2" castShadow receiveShadow geometry={nodes.平面_2.geometry} material={materials['マテリアル.002']} />
          <mesh name="平面_3" castShadow receiveShadow geometry={nodes.平面_3.geometry} material={materials['マテリアル.013']} />
        </group>
        <group name="飾り_右" position={[-1.51, 7.21, -2.7]} rotation={[-1.07, -0.64, 2.43]} scale={[0.54, 1.18, 1.18]}>
          <mesh name="Cube007_1" castShadow receiveShadow geometry={nodes.Cube007_1.geometry} material={materials['wa.black']} />
          <mesh name="Cube007_2" castShadow receiveShadow geometry={nodes.Cube007_2.geometry} material={materials['wa.red']} />
        </group>
        <mesh name="Cube007" castShadow receiveShadow geometry={nodes.Cube007.geometry} material={materials.Material} position={[0.69, 2.84, 0.85]} rotation={[-2.08, 0.63, -0.7]} scale={[-0.23, -0.41, -0.41]} />
        <mesh name="平面001" castShadow receiveShadow geometry={nodes.平面001.geometry} material={materials['hair.001']} position={[-0.54, 7.44, -1.45]} rotation={[1.58, 0, 2.49]} scale={-0.74} />
        <mesh name="Cube008" castShadow receiveShadow geometry={nodes.Cube008.geometry} material={materials.hair} position={[0.3, 6.92, -0.29]} rotation={[-3.14, 0.91, 3.14]} scale={[-2.42, -2.02, -1.7]} />
        <mesh name="立方体001" castShadow receiveShadow geometry={nodes.立方体001.geometry} material={materials.huku} position={[-0.78, 3.82, 0.01]} rotation={[Math.PI, 0.91, -1.01]} scale={[0.23, 0.38, 0.24]} />
        <mesh name="立方体" castShadow receiveShadow geometry={nodes.立方体.geometry} material={materials['マテリアル.004']} position={[-0.41, 2.86, 0.45]} rotation={[2.97, 0.91, -3]} scale={[0.95, 0.95, 0.06]} />
        <mesh name="平面002" castShadow receiveShadow geometry={nodes.平面002.geometry} material={materials['hair.001']} position={[1.2, 7.45, 0.82]} rotation={[-1.57, 0, 0.66]} scale={0.74} />
        <group name="飾り_左" position={[2.16, 7.21, 2.08]} rotation={[1.07, -0.63, 0.71]} scale={[-0.54, -1.18, -1.18]}>
          <mesh name="Cube001_1" castShadow receiveShadow geometry={nodes.Cube001_1.geometry} material={materials['wa.black']} />
          <mesh name="Cube001_2" castShadow receiveShadow geometry={nodes.Cube001_2.geometry} material={materials['wa.red']} />
        </group>
        <mesh name="Cube010" castShadow receiveShadow geometry={nodes.Cube010.geometry} material={materials.Material} position={[-0.81, 2.84, -1.04]} rotation={[-1.06, -0.63, 2.44]} scale={[-0.23, -0.41, -0.41]} />
        <mesh name="Cube011" castShadow receiveShadow geometry={nodes.Cube011.geometry} material={materials.hair} position={[0.3, 6.92, -0.29]} rotation={[0, -0.91, -3.14]} scale={[2.42, 2.02, 1.7]} />
        <mesh name="Cube012" castShadow receiveShadow geometry={nodes.Cube012.geometry} material={materials['マテリアル.010']} position={[0.82, 1.7, 0.38]} rotation={[-Math.PI, 0.91, -Math.PI]} scale={[0.38, 0.58, 0.34]} />
        <mesh name="Cube014" castShadow receiveShadow geometry={nodes.Cube014.geometry} material={materials['マテリアル.011']} position={[0.84, 0.51, 0.38]} rotation={[Math.PI / 2, 0, -2.23]} scale={[0.41, 0.39, 0.41]} />
        <mesh name="Cube001" castShadow receiveShadow geometry={nodes.Cube001.geometry} material={materials['マテリアル.011']} position={[-0.17, 0.51, -0.94]} rotation={[Math.PI / 2, 0, -2.23]} scale={[0.41, 0.39, 0.41]} />
        <group name="平面003" position={[1.25, 3.62, 0.94]} rotation={[0, -0.91, 1.82]} scale={[0.45, 2.48, 0.42]}>
          <mesh name="平面004" castShadow receiveShadow geometry={nodes.平面004.geometry} material={materials.face} />
          <mesh name="平面004_1" castShadow receiveShadow geometry={nodes.平面004_1.geometry} material={materials['マテリアル.002']} />
          <mesh name="平面004_2" castShadow receiveShadow geometry={nodes.平面004_2.geometry} material={materials['マテリアル.013']} />
        </group>
        <mesh name="立方体004" castShadow receiveShadow geometry={nodes.立方体004.geometry} material={materials.huku} position={[-0.23, 3.82, 0.7]} rotation={[0, -0.9, 2.13]} scale={[0.23, 0.38, 0.24]} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/miku_walk.glb')
