/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef,useEffect, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  // const group = useRef()
  const { nodes, materials, animations } = useGLTF('/model/zuboooooora.glb')
  // const { actions } = useAnimations(animations, group)
  const { ref, actions, names } = useAnimations(animations)
  const [index, setIndex] = useState(0)

  useEffect(() => {
    // Reset and fade in animation after an index has been changed
    actions[names[index]].reset().fadeIn(0.5).play()
    // actions[names[index+1]].reset().fadeIn(0.5).play()
    // In the clean-up phase, fade it out
    return () => actions[names[index]]
  }, [index])

  return (
    <group ref={ref} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="球002" castShadow receiveShadow geometry={nodes.球002.geometry} material={nodes.球002.material} position={[-0.27, 1.13, -0.84]} rotation={[0, 0, 0.17]} scale={[0.25, 0.22, 0.25]}/>
        <group name="球001" position={[0.27, 1.1, -0.84]} rotation={[Math.PI / 2, 0, -0.63]} scale={0.24}>
          <mesh name="球002_1" castShadow receiveShadow geometry={nodes.球002_1.geometry} material={materials.eye_big} />
          <mesh name="球002_2" castShadow receiveShadow geometry={nodes.球002_2.geometry} material={materials.eye} />
        </group>
        <mesh name="球" castShadow receiveShadow geometry={nodes.球.geometry} material={materials.body} position={[0, 1.05, 0]} scale={[0.89, 0.91, 0.89]} />
        <mesh name="円柱" castShadow receiveShadow geometry={nodes.円柱.geometry} material={materials.body} position={[0.1, 0.18, 0]} rotation={[0.05, 0.08, 0.04]} scale={[-0.07, -0.1, -0.07]} />
        <mesh name="円柱001" castShadow receiveShadow geometry={nodes.円柱001.geometry} material={materials.body} position={[0.78, 1.22, 0]} rotation={[-0.19, 0.19, 0.47]} scale={[-0.11, -0.41, -0.12]} />
        <mesh name="NURBSパス" castShadow receiveShadow geometry={nodes.NURBSパス.geometry} material={materials.マテリアル} position={[0.01, 0.85, -0.97]} rotation={[0, 0, 3.01]} scale={[-0.03, -1.07, -0.94]} />
        <mesh name="球003" castShadow receiveShadow geometry={nodes.球003.geometry} material={materials.body} position={[0, 1.05, 0]} scale={[0.89, 0.91, 0.89]} />
        <mesh name="円柱003" castShadow receiveShadow geometry={nodes.円柱003.geometry} material={materials['マテリアル.001']} position={[0.08, 2.02, 0.14]} rotation={[0, 0, -0.3]} scale={[0.09, 0.22, 0.09]} />
        <mesh name="円柱004" castShadow receiveShadow geometry={nodes.円柱004.geometry} material={materials['マテリアル.001']} position={[-0.11, 1.99, 0.14]} rotation={[0, 0, 0.56]} scale={[0.05, 0.13, 0.05]} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/zuboooooora.glb')
